spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clinicDB
    username: clinicDB
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update